java_library(
    name = "buffer",
    srcs = ["src/main/java/org/blab/commons/Buffer.java"],
)

java_test(
    name = "BufferTest",
    srcs = ["src/test/java/org/blab/commons/BufferTest.java"],
    test_class = "org.blab.commons.BufferTest",
    deps = [
        ":buffer",
        "@maven//:org_junit_jupiter_junit_jupiter_api"
    ],
)
